#ifndef        LED_MAT_CONFIG_H
#define        LED_MAT_CONFIG_H

#define HLED_MAT_R0_PIN     GPIO_PORTA,GPIO_PIN0
#define HLED_MAT_R1_PIN     GPIO_PORTA,GPIO_PIN1
#define HLED_MAT_R2_PIN     GPIO_PORTA,GPIO_PIN2
#define HLED_MAT_R3_PIN     GPIO_PORTA,GPIO_PIN3
#define HLED_MAT_R4_PIN     GPIO_PORTA,GPIO_PIN4
#define HLED_MAT_R5_PIN     GPIO_PORTA,GPIO_PIN5
#define HLED_MAT_R6_PIN     GPIO_PORTA,GPIO_PIN6
#define HLED_MAT_R7_PIN     GPIO_PORTA,GPIO_PIN7

#define HLED_MAT_C0_PIN     GPIO_PORTB,GPIO_PIN0
#define HLED_MAT_C1_PIN     GPIO_PORTB,GPIO_PIN1
#define HLED_MAT_C2_PIN     GPIO_PORTB,GPIO_PIN2
#define HLED_MAT_C3_PIN     GPIO_PORTB,GPIO_PIN3
#define HLED_MAT_C4_PIN     GPIO_PORTB,GPIO_PIN4
#define HLED_MAT_C5_PIN     GPIO_PORTB,GPIO_PIN5
#define HLED_MAT_C6_PIN     GPIO_PORTB,GPIO_PIN6
#define HLED_MAT_C7_PIN     GPIO_PORTB,GPIO_PIN7


#endif